export enum NotificationType {
  NEW_JOB_OFFER = 'NEW_JOB_OFFER',
  CONVERSATION_MESSAGE = 'CONVERSATION_MESSAGE',
  NEW_CONVERSATION = 'NEW_CONVERSATION',
  STATUS_CONVERSATION = 'STATUS_CONVERSATION',
}
