export enum SocketEnum {
  JOIN_CHAT = 'JOIN_CHAT',
  LEAVE_CHAT = 'LEAVE_CHAT',
  SEND_MESSAGE = 'SEND_MESSAGE',
  DIRECT_MESSAGE = 'DIRECT_MESSAGE',
  SEND_UPDATE = 'SEND_UPDATE',
  DELETE_MESSAGE = 'DELETE_MESSAGE',
  SETUP = 'SETUP',
}
