export { DocumentEquipment } from '../../../shared/models';
export * from './base-specs';
export * from './camera-specs';
export * from './drone-specs';
export * from './gimbal-specs';
export * from './lens-specs';
export * from './specs';
export * from './list-lenses-req';
export * from './list-lenses-res';
export * from './list-cameras-res';
export * from './list-drones-res';
export * from './list-gimbals-res';
export * from './get-equipment-specs-res';
export * from './get-equipment-specs-req';
